# Generated by Django 3.1 on 2022-04-11 05:18

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Email',
            },
        ),
    ]
